version: '3'

services:
  # Database
  pq-toolkit-db-dev:
    image: postgres
    shm_size: 128m
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

  # Database admin
  pq-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # FastAPI backend
  pq-toolkit-api-dev:
    build: ../pq-toolkit-api
    depends_on:
      pq-toolkit-db-dev:
        condition: service_healthy
    environment:
      PROJECT_NAME: $PROJECT_NAME
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_SERVER: pq-toolkit-db-dev
      FIRST_SUPERUSER_NAME: $FIRST_SUPERUSER_NAME
      FIRST_SUPERUSER_PASSWORD: $FIRST_SUPERUSER_PASSWORD
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_ENDPOINT: $MINIO_ENDPOINT
      MINIO_STORAGE_USE_HTTPS: $MINIO_STORAGE_USE_HTTPS
      PQ_API_PORT: 8787
    command: sh -c "./prestart.sh && python3 main.py"
    volumes:
      - ../pq-toolkit-api/app:/app/app

  # Frontend
  pq-toolkit-ui-dev:
    build:
      context: ../pq-toolkit-ui
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_API_URL: "htshts"
    image: pq-toolkit-ui-dev
    volumes:
      - ../pq-toolkit-ui/src:/app/src
    depends_on:
      - pq-toolkit-api-dev
    environment:
      NEXT_PUBLIC_API_URL: $PUBLIC_API_URL:$GATEWAY_PORT

  # MinIO buckets
  pq-sample-storage-minio-dev:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - minio_storage:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_STORAGE_USE_HTTPS: $MINIO_STORAGE_USE_HTTPS
    command: server --console-address ":9001" /data

  # Gateway
  pq-gateway:
    build:
      context: pq-gateway
      dockerfile: Dockerfile
    ports:
      - $GATEWAY_PORT:8000
    depends_on:
      - pq-toolkit-api-dev
      - pq-toolkit-ui-dev
    environment:
      PQ_API_SERVER: pq-toolkit-api-dev
      PQ_API_PORT: 8787
      PQ_UI_SERVER: pq-toolkit-ui-dev
      PQ_UI_PORT: 3000
